version: '2'


services:

  # Web Server
  web-server:
    image: ivasio/thesis-web-server
    build:
      dockerfile: web_server/Dockerfile
      context: .
    restart: always
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres/thesis
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    depends_on:
      - postgres
    ports:
      - "8888:8080"

  # PostgreSQL database
  postgres:
    image: ivasio/postgres
    build:
      dockerfile: Dockerfile-postgres
      context: shared
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: thesis
    ports:
     - "5431:5432"

  # Kafka and Zookeeper
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_CREATE_TOPICS: "test:1:1"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
